export const CONTROLLER_CONSTANTS = {
  AUTH: 'auth',
  USER: 'user',
  ORDER: 'order',
  TOPUP: 'topup',
  BALANCE: 'balance',
  SERVICE: 'service',
  ADMIN: 'admin',
  SERVICE_TIME: 'service_time', 
  CATEGORY: 'category',
  USER_LEVEL: 'user_level',
  V2: 'api/v2',
};
export const URL_CONSTANTS = {
  CONNECT_WALLET: 'connect_wallet',
  CREATE_USER: 'create',
  UPDATE_USER: 'update',
  CHANGE_PASSWORD: 'change-password',
  DELETE: 'delete',
  UPDATE_USER_ROLE: 'update-role',
  LIST_ADMIN: 'list-admin',
  CREATE_COLLECTION: 'create-collection',
  GET_COLLECTION_ID: '/:id',
  AUTH: 'auth',
  UPLOAD_GCP: 'image/gcp',
  ORDER_HISTORY: 'history',
  USER_ORDER_HISTORY: 'user/history/:address',
  UPDATE_USER_LEVEL: 'update-level',
};
